repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer # Remove extra new lines from EOL
  - id: fix-byte-order-marker # removes UTF-8 byte order marker
  - id: check-added-large-files
  - id: check-ast
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
    args: ['--allow-multiple-documents']
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
  - id: mixed-line-ending # Fix EOL character to Linux
    args: ['--fix','lf']
  #- id: no-commit-to-branch
  #  args: ['--branch', 'main']
  - id: pretty-format-json
  - id: trailing-whitespace # Remove white space(s) from EOL
- repo: local
  hooks:
  - id: check-filename-characters
    name: Special characters are not allowed in check-filename-characters
    entry: Filenames with special characters like space, colon, %, * ... are not allowed
    language: fail
    files: '[ ,;&$@{}<>*"%=!?]'
